-- https://wiki.hypr.land/

require("variables.variables")
require("env.env")
require("autostart.autostart")
require("monitors.monitors")
require("configs.configs")
require("windowrules.windowrules")
require("workspacerules.workspacerules")
require("permissions.permissions")
require("animations.curves")
require("animations.animations")
require("gestures.gestures")
require("binds.application_binds")
require("binds.system_binds")
require("binds.media_binds")
require("binds.window_binds")
require("binds.workspace_binds")
require("binds.plugin_binds")

hl.gesture({ fingers = 2, direction = "pinch", action = "cursorZoom", zoom_level = 2 })
-- hl.gesture({ fingers = 2, direction = "pinch", action = "cursorZoom", zoom_level = 1.2, mode = "mult" })
-- hl.gesture({ fingers = 2, direction = "pinch", action = "cursorZoom", zoom_level = 1, mode = "live" })
