-- https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        border_size     = 0,
        gaps_in         = 1,
        gaps_out        = 0,
        float_gaps      = 0,
        gaps_workspaces = 0,
        col = {
            active_border = {
                colors = {
                    0xffffffff,
                    angle = 0,
                },
            },
            inactive_border = {
                colors = {
                    0x00000000,
                    angle = 0,
                },
            },
            nogroup_border = {
                colors = {
                    0xffffaaff,
                    angle = 0,
                },
            },
            nogroup_border_active = {
                colors = {
                    0xffff00ff,
                    angle = 0,
                },
            },
        },
        layout                  = "dwindle",
        no_focus_fallback       = false,
        resize_on_border        = true,
        extend_border_grab_area = 15,
        hover_icon_on_border    = true,
        allow_tearing           = false,
        resize_corner           = 0,
        modal_parent_blocking   = false,
        locale                  = "en_US",
        snap = {
            enabled        = true,
            window_gap     = 10,
            monitor_gap    = 10,
            border_overlap = false,
            respect_gaps   = false,
        },
    },
    decoration                = {
        rounding              = 4,
        rounding_power        = 10.0,
        active_opacity        = 1.0,
        inactive_opacity      = 1.0,
        fullscreen_opacity    = 1.0,
        dim_modal             = true,
        dim_inactive          = true,
        dim_strength          = 0.2,
        dim_special           = 0.2,
        dim_around            = 0.4,
        screen_shader         = "",
        border_part_of_window = true,
        blur = {
            enabled                   = false,
            size                      = 2,
            passes                    = 3,
            ignore_opacity            = true,
            new_optimizations         = true,
            xray                      = false,
            noise                     = 0.0,
            contrast                  = 0.8916,
            brightness                = 1.0,
            vibrancy                  = 0.1696,
            vibrancy_darkness         = 0.0,
            special                   = false,
            popups                    = false,
            popups_ignorealpha        = 0.2,
            input_methods             = false,
            input_methods_ignorealpha = 0.2,
        },
        shadow = {
            enabled        = false,
            range          = 5,
            render_power   = 3,
            sharp          = false,
            color          = 0x000000aa,
            color_inactive = 0x000000aa,
            offset = {
                0,
                0,
            },
            scale          = 1.0,
        },
        glow = {
            enabled        = false,
            range          = 4,
            render_power   = 2,
            color          = 0xeeffffff,
            color_inactive = 0xeeffff88,
        },
    },
    animations = {
        enabled              = true,
        workspace_wraparound = false,
    },
    input = {
        kb_model                    = "",
        kb_layout                   = "us, ir",
        kb_variant                  = "",
        kb_options                  = "grp:rwin_toggle, grp:win_space_toggle, ctrl:nocaps, grp_led:scroll, shift:both_capslock",
        kb_rules                    = "",
        kb_file                     = "",
        numlock_by_default          = true,
        resolve_binds_by_sym        = false,
        repeat_rate                 = 40,
        repeat_delay                = 400,
        sensitivity                 = 0.0,
        accel_profile               = "adaptive",
        force_no_accel              = false,
        rotation                    = 0,
        left_handed                 = false,
        scroll_points               = "",
        scroll_method               = "2fg",
        scroll_button               = 0,
        scroll_button_lock          = false,
        scroll_factor               = 1.0,
        natural_scroll              = false,
        follow_mouse                = 1,
        follow_mouse_shrink         = 0,
        follow_mouse_threshold      = 0.0,
        focus_on_close              = 1,
        mouse_refocus               = true,
        float_switch_override_focus = 2,
        special_fallthrough         = false,
        off_window_axis_events      = false,
        emulate_discrete_scroll     = 1,
        touchpad = {
            disable_while_typing    = false,
            natural_scroll          = true,
            scroll_factor           = 1.0,
            middle_button_emulation = false,
            tap_button_map          = "lrm",
            clickfinger_behavior    = true,
            tap_to_click            = true,
            drag_lock               = 1,
            tap_and_drag            = true,
            flip_x                  = false,
            flip_y                  = false,
            drag_3fg                = 0,
        },
        touchdevice = {
            transform = -1,
            output    = "auto",
            enabled   = true,
        },
        virtualkeyboard = {
            share_states             = 2,
            release_pressed_on_close = false,
        },
        tablet = {
            transform                = -1,
            output                   = "",
            region_position          = {0, 0},
            absolute_region_position = false,
            region_size              = {0, 0},
            relative_input           = false,
            left_handed              = false,
            active_area_size         = {0, 0},
            active_area_position     = {0, 0},
        },
    },
    gestures = {
        workspace_swipe_distance                 = 300,
        workspace_swipe_touch                    = false,
        workspace_swipe_invert                   = true,
        workspace_swipe_touch_invert             = false,
        workspace_swipe_min_speed_to_force       = 30,
        workspace_swipe_cancel_ratio             = 0.5,
        workspace_swipe_create_new               = true,
        workspace_swipe_direction_lock           = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_forever                  = false,
        workspace_swipe_use_r                    = false,
        close_max_timeout                        = 1000,
    },
    group = {
        auto_group                           = true,
        insert_after_current                 = true,
        focus_removed_window                 = true,
        drag_into_group                      = 1,
        merge_groups_on_drag                 = true,
        merge_groups_on_groupbar             = true,
        merge_floated_into_tiled_on_groupbar = false,
        group_on_movetoworkspace             = false,
        col = {
            border_active = {
                colors = {
                    0x66ffff00,
                    angle = 0,
                },
            },
            border_inactive = {
                colors = {
                    0x66777700,
                    angle = 0,
                },
            },
            border_locked_active = {
                colors = {
                    0x66ff5500,
                    angle = 0,
                },
            },
            border_locked_inactive = {
                colors = {
                    0x66775500,
                    angle = 0,
                },
            },
        },
        groupbar = {
            enabled                    = true,
            font_family                = "",
            font_size                  = 8,
            font_weight_active         = "normal",
            font_weight_inactive       = "normal",
            gradients                  = false,
            height                     = 14,
            indicator_gap              = 0,
            indicator_height           = 3,
            stacked                    = false,
            priority                   = 3,
            render_titles              = true,
            text_offset                = 0,
            text_padding               = 0,
            scrolling                  = true,
            rounding                   = 1,
            rounding_power             = 2.0,
            gradient_rounding          = 2,
            gradient_rounding_power    = 2.0,
            round_only_edges           = true,
            gradient_round_only_edges  = true,
            text_color                 = 0xffffffff,
            text_color_inactive        = 0xffffffff,
            text_color_locked_active   = 0xffffffff,
            text_color_locked_inactive = 0xffffffff,
            col = {
                active = {
                    colors = {
                        0x66ffff00,
                        angle = 0,
                    },
                },
                inactive = {
                    colors = {
                        0x66777700,
                        angle = 0,
                    },
                },
                locked_active = {
                    colors = {
                        0x66ff5500,
                        angle = 0,
                    },
                },
                locked_inactive = {
                    colors = {
                        0x66775500,
                        angle = 0,
                    },
                },
            },
            gaps_in            = 2,
            gaps_out           = 2,
            keep_upper_gap     = true,
            middle_click_close = true,
            blur               = false,
        },
    },
    misc = {
        disable_hyprland_logo          = true,
        disable_splash_rendering       = true,
        disable_scale_notification     = false,
        col = {
            splash = 0xffffffff,
        },
        font_family                    = "Fira Code Nerd Font Propo",
        splash_font_family             = "Fira Code Nerd Font Propo",
        force_default_wallpaper        = -1,
        vrr                            = 1,
        mouse_move_enables_dpms        = true,
        key_press_enables_dpms         = true,
        name_vk_after_proc             = true,
        always_follow_on_dnd           = true,
        layers_hog_keyboard_focus      = true,
        animate_manual_resizes         = true,
        animate_mouse_windowdragging   = false,
        disable_autoreload             = false,
        enable_swallow                 = false,
        swallow_regex                  = "",
        focus_on_activate              = false,
        mouse_move_focuses_monitor     = true,
        allow_session_lock_restore     = false,
        session_lock_xray              = false,
        background_color               = 0x000000ff,
        close_special_on_empty         = true,
        on_focus_under_fullscreen      = 2,
        exit_window_retains_fullscreen = false,
        initial_workspace_tracking     = 0,
        middle_click_paste             = true,
        render_unfocused_fps           = 30,
        disable_xdg_env_checks         = false,
        lockdead_screen_delay          = 3000,
        enable_anr_dialog              = true,
        anr_missed_pings               = 10,
        size_limits_tiled              = false,
        disable_watchdog_warning       = true,
    },
    layout = {
        single_window_aspect_ratio           = {0, 0},
        single_window_aspect_ratio_tolerance = 0.1,
    },
    dwindle = {
        force_split                  = 0,
        preserve_split               = true,
        smart_split                  = false,
        smart_resizing               = true,
        permanent_direction_override = false,
        special_scale_factor         = 1,
        split_width_multiplier       = 1.0,
        use_active_for_splits        = true,
        default_split_ratio          = 1.0,
        split_bias                   = 0,
        precise_mouse_move           = false,
    },
    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 0.5,
        focus_fit_method = 1,
        follow_focus = true,
        follow_min_visible = 0.4,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
        wrap_focus = true,
        wrap_swapcol = true,
        direction = "right",
    },
    binds = {
        pass_mouse_when_bound             = false,
        scroll_event_delay                = 50,
        workspace_back_and_forth          = false,
        hide_special_on_workspace_change  = true,
        allow_workspace_cycles            = true,
        workspace_center_on               = 0,
        focus_preferred_method            = 0,
        ignore_group_lock                 = false,
        movefocus_cycles_fullscreen       = true,
        window_direction_monitor_fallback = true,
        disable_keybind_grabbing          = true,
        allow_pin_fullscreen              = false,
        drag_threshold                    = 0,
    },
    xwayland = {
        enabled                = true,
        use_nearest_neighbor   = true,
        force_zero_scaling     = false,
        create_abstract_socket = false,
    },
    opengl = {
        nvidia_anti_flicker = true,
    },
    render = {
        direct_scanout             = 2,
        expand_undersized_textures = true,
        xp_mode                    = false,
        ctm_animation              = 2,
        cm_enabled                 = true,
        send_content_type          = true,
        cm_auto_hdr                = 1,
        new_render_scheduling      = true,
        non_shader_cm              = 2,
        non_shader_cm_interop      = 2,
        cm_sdr_eotf                = "default",
        commit_timing_enabled      = true,
        use_fp16                   = 1,
        keep_unmodified_copy       = 2,
        use_shader_blur_blend      = false,
    },
    cursor = {
        invisible                       = false,
        sync_gsettings_theme            = true,
        no_hardware_cursors             = 2,
        no_break_fs_vrr                 = 2,
        min_refresh_rate                = 60,
        hotspot_padding                 = 1,
        inactive_timeout                = 10,
        no_warps                        = false,
        persistent_warps                = false,
        warp_on_change_workspace        = 0,
        warp_on_toggle_special          = 0,
        default_monitor                 = "",
        zoom_factor                     = 1.0,
        zoom_rigid                      = false,
        zoom_detached_camera            = false,
        enable_hyprcursor               = true,
        hide_on_key_press               = false,
        hide_on_touch                   = true,
        hide_on_tablet                  = true,
        use_cpu_buffer                  = 2,
        warp_back_after_non_mouse_input = false,
        zoom_disable_aa                 = true,
    },
    ecosystem = {
        no_update_news      = true,
        no_donation_nag     = true,
        enforce_permissions = true,
    },
    quirks = {
        prefer_hdr = 0,
    },
})
